### ISSUE TITLE
Remove non-ascii characters in JSON files

### ISSUE THREAD

**Issue by hsercanatli** [sertansenturk/tomato#59]
In temporary JSON files generated by MATLAB binaris;

such as in tempo.json;

{
	"scoreInformed": {
		"relative": {
			"Method": "scoreInformed",
			"Citation": "Holzapfel, A., imekli U., entrk S., and Cemgil A. T. (2015). Section-level Modeling of Musical Audio for Linking Performances to Scores in Turkish Makam Music. In Proceedings of IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP), Brisbane, Australia.",
			"RelativeTo": "ussak--sazsemaisi--aksaksemai----neyzen_aziz_dede/ussak--sazsemaisi--aksaksemai----neyzen_aziz_dede.txt",
			"Value": 1.110344828

**Comment by sertansenturk** [comment]
Let's try adding `subprocess_env["LANG"] = "en_US.utf8"` below https://github.com/sertansenturk/tomato/blob/master/tomato/bincaller.py#L29

**Comment by sertansenturk** [comment]
The above code fixed the issue.
