### ISSUE TITLE
 list index out of range on score analysis 

### ISSUE THREAD

**Issue by andrebola** [sertansenturk/tomato#62]
This happend to around 100 files, for example:
050419a5-61b9-4988-9047-c717260d867f (suzinak_zirgule--kupe--devrirevanihindi--perdebazim--ahmet_avni_konuk)

File "/srv/dunya/env/src/tomato/tomato/symbolic/symbtranalyzer.py", line 50, in analyze
    input_f['mbid'] = self._get_first(input_f['mbid'])
  File "/srv/dunya/env/src/tomato/tomato/analyzer.py", line 70, in _get_first
    return feature[0]  # for now get the first feature
IndexError: list index out of range

**Comment by sertansenturk** [comment]
This was a case when the input SymbTr-name is not the same in the latest SymbTr branch, hence the symbtr-mbid dictionary returns no matches. Partial caller is extended to handle this case.

I'll keep the issue until we release a version with all the bugfixes.
