### ISSUE TITLE
Tonic tempo computation error

### ISSUE THREAD

**Issue by andrebola** [sertansenturk/tomato#65]
When running joint analysis I see this error, for example for the file :
/incoming/Turkey-makam/audio/bekir_unluataer__turk_muziginde_cagdas_donem/14_kurdilihicazkar--sarki--curcuna--bitmez_tukenmez--selahattin_icli.mp3

Too many outputs requested.  Most likely cause is missing [] around left hand side that has a comma separated list expansion.

Error in fragmentLinker.ScoreReader.getScoreFragments>section2interval (line 172)

Error in fragmentLinker.ScoreReader.getScoreFragments (line 58)

Error in fragmentLinker.TonicIdentifier/identify (line 34)

Error in fragmentLinker.TonicTempoTuningExtractor/estimate (line 12)

Error in extractTonicTempoTuning (line 62)

MATLAB:TooManyOutputsDueToMissingBraces

**Comment by sertansenturk** [comment]
This was a special case where the section information was not indicated in the lyrics column of the score. The latest SymbTr branch has the score fixed.

Though I think there will be similar cases where I can fix easily. Can you give me a list of audio-score pairs which give the same error? A simple tsv file would suffice.

**Comment by andrebola** [comment]
I think I have the same error with the file:
smanli_da_muzik__mevlevi_ayinleri_ve_bektasi_nefesleriIII/02_-_bektasi_nefesleri.mp3

Too many outputs requested.  Most likely cause is missing [] around left hand side that has a comma separated list expansion.

Error in fragmentLinker.ScoreReader.getScoreFragments>section2interval (line 172)



Error in fragmentLinker.ScoreReader.getScoreFragments (line 58)



Error in fragmentLinker.TonicIdentifier/identify (line 34)



Error in fragmentLinker.TonicTempoTuningExtractor/estimate (line 12)



Error in extractTonicTempoTuning (line 62)



MATLAB:TooManyOutputsDueToMissingBraces

**Comment by andrebola** [comment]
The same for the file:

Ney_ile_Icra_Edilmis_Saz_Eserleri/sedd-i_araban_pesrev__kz_ney_.mp3

**Comment by sertansenturk** [comment]
We have to figure out which score is the problematic one in the first recording: http://musicbrainz.org/recording/83d8e8cd-cc4a-4fc1-9995-5fc3da588f16

The second example: it worked in my local :disappointed: The score has not changed so I'm not sure what's wrong...

**Comment by andrebola** [comment]
barkcin_sarigul_erdal_erdem_kutlu__can_sesi_ask_nefesi/08_beyati--kupe_37_--duyek--mutriba--ahmet_avni_konuk.mp3

12--acemkurdi--sarki--senginsemai--ruzgar_uyumus--refik_fersan.mp3

MuratAydemir_MakamGuide1/1-50_beyati_saz_semaisi__kanuni_omer_efendi_.mp3

barkcin_sarigul_erdal_erdem_kutlu__can_sesi_ask_nefesi/17_-_hicaz_terennum.mp3

Ney_ile_Icra_Edilmis_Saz_Eserleri/acemasiran_pesrev__kz_ney__1.mp3

Kanuni_19secmeKlasikEser/03_karanfil_oylum_oylum_-_istanbul_turkusu.mp3

bestekar_padisahlarin_sozlu_eserleri/09_mahur--tavsanca--aksak--aldi_aklim--ii._mahmud-0021.mp3

ermeni_bestekarlar__vol_2/12--muhayyerkurdi--pesrev--devrikebir----asdik_aga.mp3

ittmt_sultan_bestekarlar_mehter/02_beyati--yuruksemai--senginsemai--gelse_nesim-i--ali_ufki.mp3

bestekar_iii._selim_han__2/09_ey_serv-i.mp3

ergin_kizilay__tm_de_ud_ile_anilar_-_1_enst/10_gurub_etti_gunes.mp3

bestekar_iii._selim_han__2/12_suzidilara--yuruksemai--yuruksemai--ab_u_tab--iii_selim.mp3

Kanuni_19secmeKlasikEser/06_olmaz_ilac_sineyi_sad_pareme.mp3

tanburi_cemil_bey__vol_2/1-02_huseyni--oyunhavasi--nimsofyan--cecen_kizi--tanburi_cemil_bey.mp3

**Comment by sertansenturk** [comment]
Ok, I tried it for these three and ended up in the same situation where my local just worked or there were no sections from the start with.

Ney_ile_Icra_Edilmis_Saz_Eserleri/acemasiran_pesrev__kz_ney__1.mp3 -> worked

Kanuni_19secmeKlasikEser/06_olmaz_ilac_sineyi_sad_pareme.mp3 -> worked

tanburi_cemil_bey__vol_2/1-02_huseyni--oyunhavasi--nimsofyan--cecen_kizi--tanburi_cemil_bey.mp3 -> no score section

I think I will deal with the no section issue for the tonicTempoTuning, but the other I don't know ow to approach...

**Comment by andrebola** [comment]
There are 2000 failed recording, for what I saw almost all because of this error. I think there is no recording successfully processed for this extractor, ince the other 4000 don't have scores.

**Comment by sertansenturk** [comment]
Ok I've realized that tonicTempoTuning error has a simple workaround. Tha error should be fixed now.

We should only be seeing the mysterious error we are getting in the server and not in my local

**Comment by sertansenturk** [comment]
@andrebola is this fixed?

**Comment by sertansenturk** [comment]
Ney_ile_Icra_Edilmis_Saz_Eserleri/acemasiran_pesrev__kz_ney__1.mp3 and Kanuni_19secmeKlasikEser/06_olmaz_ilac_sineyi_sad_pareme.mp3 also wprks in the server.

 We are trying to solve the issue with tanburi_cemil_bey__vol_2/1-02_huseyni--oyunhavasi--nimsofyan--cecen_kizi--tanburi_cemil_bey.mp3  (no tonic or tempo computed)

**Comment by sertansenturk** [comment]
The issue related to Cecen kizi is it is related to a recording instead of a work. Dunya does not handle this case. I will close this issue and open another one in Dunya issues regarding this problem.
